CREATE DATABASE IF NOT EXISTS petshop;
USE petshop;

CREATE TABLE IF NOT EXISTS respostas_questionario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  q1 VARCHAR(100),
  q2 VARCHAR(100),
  q3 VARCHAR(100),
  q4 VARCHAR(100),
  q5 TEXT,
  q6 VARCHAR(100),
  q7 VARCHAR(100),
  q8 VARCHAR(100),
  q9 VARCHAR(100),
  q10 VARCHAR(100),
  data_resposta TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
